GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTI2ODI3OTcsImV4cCI6MTc1MjY4Mjg1N30.y4VdSyYSzMaZGDIeGwxgvsHHhlDwA7kjz1Ng1Wkqras

###



DELETE http://localhost:4000/logout
Content-Type: application/json
{
    "token": 
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTI2ODM1OTd9.-ZPHoHWf_AHAEQvlL2AUOTJVOXGk8HZj4kMLjOOpOvs"
}


###



POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "admin"
}

###


POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : 
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTI2ODM1OTd9.-ZPHoHWf_AHAEQvlL2AUOTJVOXGk8HZj4kMLjOOpOvs"
}